version: '3.3'

services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=product-service
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    volumes:
      - ./data/mongodb:/data/db
    restart: always
